### ISSUE TITLE
Erro ao instalar o anaconda: "Failed to create menus"

### ISSUE THREAD

**Issue by HugoLeo1976** [totvslabs/carol-ds-academy#10]
Ocorre o Erro abaixo ao instalar o anaconda: 
"Failed to create menus"
![image](https://user-images.githubusercontent.com/55465208/65082305-fc620d80-d97b-11e9-92bf-7cbc8c42f08b.png)

Como devo proceder?

**Comment by rafarui** [comment]
Tentou instalar a versao 32b?
teve um pessoal com problema parecido que instalando a 32b resolveu.

**Comment by HugoLeo1976** [comment]
Tentei instalar a versão 32 bits e foi ok, obrigado.
Pode encerrar a Issue.
