### ISSUE TITLE
Disponibilização de aulas gravadas

### ISSUE THREAD

**Issue by danielmarquini** [totvslabs/carol-ds-academy#11]
Boa Tarde,

As aulas serão disponibilizadas para quem não conseguir assistir ao vivo ou teve problemas durante a transmissão? Como faço para acessar?

Obrigado.

**Comment by alisonkaique** [comment]
Boa Tarde, Daniel.

Foi dito na primeira aula que farão a edição das aulas online e disponibilizarão na Universidade TOTVS.
Quanto ao prazo, creio que seja após a finalização das aulas online.

**Comment by danielmarquini** [comment]
Eu tive problemas no audio durante a primeira aula, precisava revê-la. E hj surgiu um imprevisto num cliente e não conseguirei assistir ao vivo, o que vai ficar ruim para a terceira aula, pois não terei visto os conteúdos anteriores. Não seria possível disponibilizar mesmo sem a edição? Acredito que outras pessoas que tb estão inscritas no curso possam estar passando por situação parecida. Se esperarmos até o final para termos este conteúdo vai ficar ruim não?

**Comment by ajuver** [comment]
Eu também não conseguirei assistir ao vivo a aula de hoje, quando essa aula estará disponível para que eu possa assistir?

**Comment by danielmarquini** [comment]
Então... do q adianta disponibilizar a aula gravada só no final do curso??? @alisonkaique ... ajuda ae

**Comment by alisonkaique** [comment]
Daniel, eu não sou da equipe responsável.

Só comentei que ouvi isso na primeira aula, de que iriam editar e disponibilizar tudo na Universidade TOTVS. Os demais detalhes acho que o pessoal da equipe do curso vai saber responder.

**Comment by danielmarquini** [comment]
Ahh tá;... pensei q tu era da equipe....desculpe... 

Alô responsáveis... podem nos ajudar?

**Comment by rafarui** [comment]
Apos a primeira faze iremos disponibilizar os videos. Antes de comecar a parte mais teorica.
