### ISSUE TITLE
Gravações Aulas 1 e 2

### ISSUE THREAD

**Issue by evanstos** [totvslabs/carol-ds-academy#13]
Boa Tarde,

Estava em cliente e não consegui acompanhar as aulas 1 e 2, é possível disponibilizar o conteúdo ?

att,
Evandro dos Santos

**Comment by rafarui** [comment]
> Boa Tarde,
> 
> Estava em cliente e não consegui acompanhar as aulas 1 e 2, é possível disponibilizar o conteúdo ?
> 
> att,
> Evandro dos Santos
ola,

Iremos disponibilizar no inicio de outubro.
