### ISSUE TITLE
Integração Carol com ferramentas de Chatbot

### ISSUE THREAD

**Issue by robsonribeiro-bh** [totvslabs/carol-ds-academy#17]
Bom dia, 

Surgiu uma dúvida com relação a Carol e sei que foge neste momento do material discutido no curso, porém se for possível necessito entender um pouco mais sobre um cenário de uso que está surgindo para integração. A Carol é uma concorrente do Watson da IBM? A mesma poderia ser integrada com alguma ferramenta de Chatbot para reconhecimento cognitivo (integração com a Blip)? A ideia do projeto seria com base na interação de alunos via Blip, utilizarmos a nossa base de conhecimento TOTVS para reconhecermos padrões e dispararmos processos em nossos sistemas.

**Comment by rafarui** [comment]
> Bom dia,
> 
> Surgiu uma dúvida com relação a Carol e sei que foge neste momento do material discutido no curso, porém se for possível necessito entender um pouco mais sobre um cenário de uso que está surgindo para integração. A Carol é uma concorrente do Watson da IBM? A mesma poderia ser integrada com alguma ferramenta de Chatbot para reconhecimento cognitivo (integração com a Blip)? A ideia do projeto seria com base na interação de alunos via Blip, utilizarmos a nossa base de conhecimento TOTVS para reconhecermos padrões e dispararmos processos em nossos sistemas.

Ola Robson,

me chama no hangouts ou por email que podemos discutir melhor sobre isso. Vamos deixar esse forum pra tirar duvidas especificas do curso.
