### ISSUE TITLE
Python for Beginners by M$

### ISSUE THREAD

**Issue by nicociri** [totvslabs/carol-ds-academy#18]
Para quien este recien comenzando en Python, Microsoft publico una serie de videos tutoriales.
For anybody who's just beginning with Python, Microsoft published a series of tutorials.
Nao sei como dizer isto en portugues... ¯\_(ツ)_/¯

https://www.youtube.com/playlist?list=PLlrxD0HtieHhS8VzuMCfQD4uJ9yne1mE6

**Comment by rafarui** [comment]
Good material @nicociri , tks for sharing.
