### ISSUE TITLE
Horário alternativo para as aulas

### ISSUE THREAD

**Issue by tmansur** [totvslabs/carol-ds-academy#19]
Boa noite a todos.
Seria possível mudarmos o horário das aulas para as 19 horas? Saio da TOTVS BH as 17h30 e não consigo chegar em casa a tempo de acompanhar toda a aula, sempre perco entre 20 a 40 minutos, o que prejudica muito o aprendizado (a não disponibilização dos vídeos logo após a aula prejudica ainda mais o entendimento).  
Não sei se esse é o cenário de mais pessoas que estão acompanhando o curso, caso seja apenas o meu, a disponibilização do vídeo da aula no dia seguinte já ajudaria bastante.

**Comment by raquelhager** [comment]
Bom dia,

O que mais está impactando para mim é a falta de calendário e a disponibilização do vídeo das aulas anteriores
Depois de 3 aulas seguidas às quarta-feiras eu imaginei que todas seriam neste dia da semana e assumi compromissos (também voltados à educação) de terça-feira.

Gostaria de entender se as aulas continuarão a mudar de dias e quando será feita a publicação dos vídeos.

@rafarui

**Comment by rafarui** [comment]
> Boa noite a todos.
> Seria possível mudarmos o horário das aulas para as 19 horas? Saio da TOTVS BH as 17h30 e não consigo chegar em casa a tempo de acompanhar toda a aula, sempre perco entre 20 a 40 minutos, o que prejudica muito o aprendizado (a não disponibilização dos vídeos logo após a aula prejudica ainda mais o entendimento).
> Não sei se esse é o cenário de mais pessoas que estão acompanhando o curso, caso seja apenas o meu, a disponibilização do vídeo da aula no dia seguinte já ajudaria bastante.

Acho que nao vai ser possivel mudar nao. Tem muita gente que assiste direto da totvs, por isso essa hora. Estamos trabalhando pra deixar os videos live o mais rapido possivel.

**Comment by rafarui** [comment]
> Bom dia,
> 
> O que mais está impactando para mim é a falta de calendário e a disponibilização do vídeo das aulas anteriores
> Depois de 3 aulas seguidas às quarta-feiras eu imaginei que todas seriam neste dia da semana e assumi compromissos (também voltados à educação) de terça-feira.
> 
> Gostaria de entender se as aulas continuarão a mudar de dias e quando será feita a publicação dos vídeos.
> 
> @rafarui

Oi Raquel, 
Entendo seu ponto, nao esta nas nossas maos disponibilizar os videos. Eh o pessoal da universidade TOTVS que esta trabalhando na liberacao dos videos. Ontem mesmo eles mandaram um material pra validar. 

Acredito que ate o final dessa semana iremos liberar os videos das primeiras aulas. 
Quanto a data, era pra ser todas as quartas, eu tive problemas com horarios e tivemos que marcar pra terca feira.

**Comment by vgoetten** [comment]
Olá pessoal, as aulas ao vivo serão sempre na quarta-feira. Esta semana foi extraordinário porque amanhã no final da tarde o Rafael vai estar em viagem para o Brasil.
Na aula de hoje o @rafarui vai trazer novidades sobre os vídeos das aulas anteriores :)
