### ISSUE TITLE
Problemas instalação anaconda

### ISSUE THREAD

**Issue by AlexandreWeber** [totvslabs/carol-ds-academy#2]
Pessoal, 

Instalei o anaconda 3.7 (Windows 10) porém o anaconda navigator aparece pra mim.

Alguma dica do que pode ser?

**Comment by AlexandreWeber** [comment]
Com a versão 32bits a instalação ocorreu com sucesso!

**Comment by felipecrescencio** [comment]
Pessoal, vi no ([stackoverflow](https://stackoverflow.com/a/57274015)) que essa instalação do Anaconda3 pode ter problemas com alguns antivírus.

A instalação 64bits de dezembro/2018 funcionou em alguns notebook que apresentaram o problema de não instalar o Anaconda3 Navigator.

Se quiserem instalar essa versão, podem baixá-la [aqui](https://repo.continuum.io/archive/Anaconda3-2018.12-Windows-x86_64.exe).

**Comment by JosiYokota** [comment]
> Pessoal, vi no ([stackoverflow](https://stackoverflow.com/a/57274015)) que essa instalação do Anaconda3 pode ter problemas com alguns antivírus.
> 
> A instalação 64bits de dezembro/2018 funcionou em alguns notebook que apresentaram o problema de não instalar o Anaconda3 Navigator.
> 
> Se quiserem instalar essa versão, podem baixá-la [aqui](https://repo.continuum.io/archive/Anaconda3-2018.12-Windows-x86_64.exe).

Show!! O meu Navigator tb não estava aparecendo, desinstalei e instalei essa versão de 2018 e agora deu certo! Obrigada!
