### ISSUE TITLE
Calendário Aulas

### ISSUE THREAD

**Issue by danielmarquini** [totvslabs/carol-ds-academy#20]
Bom Dia pessoal,

Temos vários compromissos e nem sempre é fácil nos agendarmos, espero que compreendam nosso lado. As aulas não seriam toda quarta? Aula hj? 

Tem como pelo menos disponibilizar um calendário das próximas? Fica complicado acompanhar assim, cada semana um agendamento diferente.

Obrigado.

**Comment by danielmarquini** [comment]
O melhor seria disponibilizar off line logo após a aula ao vivo, resolveria o problema.

**Comment by rafarui** [comment]
Oi Daniel, era pra ser todas as quartas, eu tive problema de agenda e nao conseguirei essa quarta feira. 

Disponibilizar os videos nao depende somente de nos, o time da universidade tbm esta trabalhando nisso. 
Vou perguntar pra eles se nao conseguimos disponibilizar os videos logo depois das aulas sem edicoes pra tentar acelar.

Mas ate o final dessa semana acredito que ja estara disponivel o portal inde iremos colocar os videos.
