### ISSUE TITLE
users[(users['email_verified']==False)]

### ISSUE THREAD

**Issue by douglasfsouza** [totvslabs/carol-ds-academy#22]
Boa noite,
A instrução users[(users['email_verified']==True)] está funcionando bem, mas quando faço a inversão não traz nada mesmo existindo vários registros com False
users[(users['email_verified']==False)]

Sabe o que pode ser ?

**Comment by rafarui** [comment]
Aqui parece esta funcionando normal. Como vc esta fazendo?

![image](https://user-images.githubusercontent.com/24738559/66203214-2571e600-e67e-11e9-992a-8b7bb475a722.png)
![image](https://user-images.githubusercontent.com/24738559/66203226-2c98f400-e67e-11e9-888d-b9359d20dcc2.png)



Vc mudou essa coluna por acaso? tente `users['email_verified'].dtype` . Isso tem que aparecer como `bool`.

Outra coisa, como essa eh uma coluna do tipo `bool`, vc pode fazer simplesmente,

`users[(users['email_verified'])] ` para pegar os `True` e
`users[(~users['email_verified'])] ` para pegar os `False`

**Comment by douglasfsouza** [comment]
Boa tarde,
Depois que recarreguei o arquivo passou a funcionar bem, como você disse devo ter alterado alguma configuração, mas estranho é por que com True estava funcionando bem, fiz de diversas formas, com True, 1, usando variável pré-definida, aí quando invertia com ~, False ou 0 mostrava só o cabeçalho, não consigo mais simular, se ocorrer novamente te aviso, vlw!!
