### ISSUE TITLE
Banco de Dados mais utilizado.

### ISSUE THREAD

**Issue by BrunoGiles** [totvslabs/carol-ds-academy#23]
Boa tarde pessoal, tudo bem?

Gostaria de saber pela experiência de vocês, qual é o Banco de Dados mais utilizado nessa área, levando em conta até mesmo quando vamos trabalhar com uma grande massa de dados(Big Data).

Desde já agradeço.

**Comment by rafarui** [comment]
Não existe uma reposta pra isso. Depende do use case que vc tem vc tem q escolher o que mais se adequa.

Existe uma muitos bancos bem comuns. A se falarmos de nosql temos 
Memcached, Redis, Coherence, Hbase, BigTable, Accumulo, MongoDB, CouchDB, hive. 
SQL temos os mesmos de sempre, SQL Server, MySQL, PostgresSQL, Oracle. 

Muitas coisas em big data tbm utilizam frameworks pra stream de dados e não data bases. Tipo
Kafka, spark, haadop. 

Todos tem vantagens e desvantagens. Vai depender de sua aplicação
