### ISSUE TITLE
Cronograma das próximas aulas

### ISSUE THREAD

**Issue by MirandaTOTVSBH** [totvslabs/carol-ds-academy#25]
Prezados, boa noite!

Poderiam disponibilizar a grade das próximas aulas? 
Serão realizadas todas as terças-feiras de 18:00 às 19:30?

**Comment by vanderlucioevaristo** [comment]
Precisamos conseguir nos programar gente! Hoje por exemplo eu perdi aula
pois estava achando que era amanhã e marquei compromisso hoje. Foi nos
informado semana passada que era uma eventualidade. Eu

Em ter, 22 de out de 2019 às 19:19, MirandaTOTVSBH <notifications@github.com>
escreveu:

**Comment by rafarui** [comment]
Acabei de adicionar no git
https://github.com/totvslabs/carol-ds-academy

**Comment by vanderlucioevaristo** [comment]
Gente,
Nem parece que a gente trabalha com tecnologia. Cria uma agenda no Google e
compartilha o link com todos do curso. Aí todo mundo assina ela é pronto.
Qq mudança já tá na tela de todo mundo! Simples assim. Acabei o curso só
cancelar a assinatura.

Em qua, 23 de out de 2019 às 18:50, Rafael Rui <notifications@github.com>
escreveu:
