### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by ghost** [totvslabs/carol-ds-academy#28]
Opá,

Infelizmente acabei não podendo comparecer na última aula (Recap 06) e fiquei meio perdido como prosseguirá a formação daqui em diante, 
Quando e onde começa os próximos passos?

Abraço.

**Comment by rafarui** [comment]
> Opá,
> 
> Infelizmente acabei não podendo comparecer na última aula (Recap 06) e fiquei meio perdido como prosseguirá a formação daqui em diante,
> Quando e onde começa os próximos passos?
> 
> Abraço.

Ola,
Proximo passo eh oq estamos chamando de mastering in Carol. Que tem como objetivo ensinar como usar a plataforma Carol pra desenvolver um modelo/app de machine learning. 

Segundo o pessoal da universidade, o lancamento sera na primeira semana de dezembro.
