### ISSUE TITLE
Mastering in Carol

### ISSUE THREAD

**Issue by pvdebarba** [totvslabs/carol-ds-academy#29]
Opa,

Temos alguma estimativa de quando será liberado as aulas de mastering in Carol?

Abraço!

**Comment by rafarui** [comment]
> Opa,
> 
> Temos alguma estimativa de quando será liberado as aulas de mastering in Carol?
> 
> Abraço!

Ola, Já está liberado na plataforma da universidade totvs.

**Comment by pvdebarba** [comment]
Opa!

Agora que vi que foi criado uma nova trilha.

Valeu, Rafa!
