### ISSUE TITLE
Universidade TOTVS

### ISSUE THREAD

**Issue by AnaClarice382** [totvslabs/carol-ds-academy#30]
As aulas estão disponíveis para rever na universidade TOTVS? Se sim, não consigo mais acessar..

**Comment by rafarui** [comment]
Vc pode encontrar os dois aqui
https://universidadetotvs.com.br/skin/atena/home

**Comment by AnaClarice382** [comment]
Esse link fica redirecionando e nem consegue carregar a página

**Comment by rafarui** [comment]
> Esse link fica redirecionando e nem consegue carregar a página

Deve redirecionar pra vc fazer o login com o fluig.

**Comment by AnaClarice382** [comment]
Acho que não, testei fora rede TOTVS, ele me direciona realmente para o fluig, e dps de logar que ele se perde e fica redirecionando. Pedi para outras pessoas testarem tb e não rolou. Pode ser algo de permissão?

**Comment by rafarui** [comment]
> Acho que não, testei fora rede TOTVS, ele me direciona realmente para o fluig, e dps de logar que ele se perde e fica redirecionando. Pedi para outras pessoas testarem tb e não rolou. Pode ser algo de permissão?

Ana, falei com o pessoal da universidade.
Parece que vai ser oficializado dia 20/03. dai todos vao conseguir acessar. Dai vai estar liberado pra todos a plataforma.

**Comment by AnaClarice382** [comment]
Ah sim, beleza, muito obrigada Rafa ^^
