### ISSUE TITLE
Instalação Anaconda

### ISSUE THREAD

**Issue by suseteeccher** [totvslabs/carol-ds-academy#6]
Estou com problemas na instalação do Anaconda.
Eu instalei conforme procedimento, as pastas foram criadas, porém ao procurar o aplicativo para iniciar, não encontra.
Não é localizado nem o Navigator e nem o Prompt do Conda.
Ao tentar executar o comando "conda" no prompt do windows, diz que o comando não é válido.

Minha máquina tem 8Gg de RAM, mas a TI disse que esse não é o problema. O que poderia ser ?

**Comment by lmagalhaesbr** [comment]
> Estou com problemas na instalação do Anaconda.
> Eu instalei conforme procedimento, as pastas foram criadas, porém ao procurar o aplicativo para iniciar, não encontra.
> Não é localizado nem o Navigator e nem o Prompt do Conda.
> Ao tentar executar o comando "conda" no prompt do windows, diz que o comando não é válido.
> 
> Minha máquina tem 8Gg de RAM, mas a TI disse que esse não é o problema. O que poderia ser ?

Não sei se te ajuda, mas algumas pessoas estão tendo problemas na instalação da versão 64 bits, mas conseguem usar a 32 normalmente.

**Comment by alisonkaique** [comment]
Estava tendo o mesmo problema com a versão 64, porém ainda não tinha visto o feedback do pessoal quanto a versão 32.
Mas instalei a versão 64 diretamente pelo Visual Studio e funcionou normalmente. Fica aí mais uma possibilidade.

**Comment by suseteeccher** [comment]
Realmente funcionou, Obrigada 👍

**Comment by felipecrescencio** [comment]
Pessoal, vi no ([stackoverflow](https://stackoverflow.com/a/57274015)) que essa instalação do Anaconda3 pode ter problemas com alguns antivírus.

A instalação 64bits de dezembro/2018 funcionou em alguns notebook que apresentaram o problema de não instalar o Anaconda3 Navigator.

Se quiserem instalar essa versão, podem baixá-la [aqui](https://repo.continuum.io/archive/Anaconda3-2018.12-Windows-x86_64.exe).
