### ISSUE TITLE
Problema Instalação Anaconda no Win7

### ISSUE THREAD

**Issue by eduardomenezes9** [totvslabs/carol-ds-academy#7]
Bom dia!
Pessoal, tentei fazer a instalação do Anaconda 2019.07 Phyton 3.7 no meu PC algumas vezes e não consegui. A instalação acontece muito rapidamente (menos de 1 minuto) mas depois eu não consigo abrir nem o prompt e nem o navigator.

Será que o problema é o Windows 7? Vocês sabem se tem problemas de compatibilidade com essa versão?

Qualquer coisa me chamem no hangout, por favor. **eduardo.menezes**

Obrigado!

**Comment by mcgazafi** [comment]
Boa tarde.
Tive o mesmo erro na instalação do Anaconda3 2019.07 Phyton 3.7 para o windows 10...  Só consegui solucionar baixando a liberação Anaconda3 2019.03 pelo link https://repo.continuum.io/archive/

**Comment by eduardomenezes9** [comment]
Obrigado Marcos!
Consegui proceder com a instalação pelo link enviado
