### ISSUE TITLE
Leitura recomendavel?

### ISSUE THREAD

**Issue by nicociri** [totvslabs/carol-ds-academy#8]
Boa tarde!
Vcs poderiam recomendar literaturas sobre o tema? (si tiveram os pdfs melhor....)

Da pra adiantar conhecimiento?

obrigado!

**Comment by rafarui** [comment]
> Boa tarde!
> Vcs poderiam recomendar literaturas sobre o tema? (si tiveram os pdfs melhor....)
> 
> Da pra adiantar conhecimiento?
> 
> obrigado!

EU gosto bastante desse livro. 
https://www.ime.unicamp.br/~dias/Intoduction%20to%20Statistical%20Learning.pdf

A unica falha dele eh ser em R nao em python. heheh
Mas pra quem esta iniciando, ele eh bem ditatico.

**Comment by nicociri** [comment]
Rafa, voy a ser honesto contigo.. lei hasta el capitulo 5... le perdi perdon a Dios y me puse a llorar 😄 . No estoy entendiendo casi nada del libro. No por el ingles, sino por el tema. Puede alguien hacer uso de Carol como herramienta, sin entender cuales son las bases de probabilidad y estadistica que contiene este libro? Tiene sentido continuar?
------------
google translate:
Rafa, vou ser sincero com você ... li até o capítulo 5 ... pedi desculpas a Deus e comecei a chorar. Não estou comprendendo quase nada do livro. Não por o inglês, mas por o assunto. Alguém pode usar Carol como uma ferramenta, sem entender quais são as bases de probabilidade e estatística contidas neste livro? Faz sentido continuar?

**Comment by rafarui** [comment]
Olá Nico,
Vc pode sim. Na mastering in Carol, que será apresentado na sequência desse curso vamos mostrar como usar a Carol como ferramenta sim. 

A idea do academy eh mostrar o caminho pra se tornar um cientista de dados pleno, logo eh importante toda essa base. Existe frameworks que permitem usar essas ferramentas de Machine Learning sem entender a base, mas entender oq esta acontecendo eh exencial pra se tonar um cientista de dados
