### ISSUE TITLE
Instalar um novo ambiente

### ISSUE THREAD

**Issue by totvs-adrianoc** [totvslabs/carol-ds-academy#9]
Creio que tem um comando errado no guia de exercícios da primeira aula. Na parte de "Installing a new environment (kernel) in the jupyter notebook", o primeiro comando creio que seja "conda create" e não "conda install".

**Comment by rafarui** [comment]
> Creio que tem um comando errado no guia de exercícios da primeira aula. Na parte de "Installing a new environment (kernel) in the jupyter notebook", o primeiro comando creio que seja "conda create" e não "conda install".

Corrigido, https://github.com/totvslabs/carol-ds-academy/commit/c9f70f25404b0563f5a8ec6ad37a6624409166e0

obrigado
